# Generated by Django 3.0.8 on 2020-08-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='pd_Notification',
        ),
    ]
